# Generated by Django 3.2.5 on 2021-12-03 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurls',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 20, 57, 6, 361882)),
        ),
    ]
