# Generated by Django 3.2.5 on 2021-12-24 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0005_alter_myurls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurls',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 24, 18, 43, 37, 240280)),
        ),
    ]
