# Generated by Django 3.2.5 on 2022-06-25 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0008_alter_myurls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurls',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 25, 17, 57, 41, 428175, tzinfo=utc)),
        ),
    ]
