# Generated by Django 3.2.5 on 2021-12-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
